# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'denglu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_MainWindow(object):
    def setupUi(self, login_MainWindow):
        login_MainWindow.setObjectName("MainWindow")
        login_MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        login_MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(login_MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 70, 90, 30))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 170, 90, 30))
        self.label_2.setObjectName("label_2")

        self.lineEdit_yonghu = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_yonghu.setGeometry(QtCore.QRect(300, 70, 150, 40))
        self.lineEdit_yonghu.setObjectName("lineEdit_yonghu")

        self.lineEdit_mima = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_mima.setGeometry(QtCore.QRect(300, 170, 150, 40))
        self.lineEdit_mima.setObjectName("lineEdit_mima")

        self.pushButton_denglu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_denglu.setGeometry(QtCore.QRect(300, 270, 150, 40))
        self.pushButton_denglu.setObjectName("pushButton_denglu")

        login_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(login_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(login_MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "登录"))
        self.label.setText(_translate("MainWindow", "用户名"))
        self.label_2.setText(_translate("MainWindow", "密码"))
        self.pushButton_denglu.setText(_translate("MainWindow", "登录"))
        self.pushButton_denglu.setShortcut(_translate("login_MainWindow", "Enter")) #设置快捷键