# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'function.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from xunlian import *



class Ui_xunlian_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton_chakan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_chakan.setGeometry(QtCore.QRect(300, 70, 180, 40))
        self.pushButton_chakan.setObjectName("pushButton_chakan")

        self.pushButton_xunlian = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_xunlian.setGeometry(QtCore.QRect(300, 160, 180, 40))
        self.pushButton_xunlian.setObjectName("pushButton_xunlian")
        MainWindow.setCentralWidget(self.centralwidget)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "功能"))
        self.pushButton_chakan.setText(_translate("MainWindow", "查看数据"))
        self.pushButton_xunlian.setText(_translate("MainWindow", "训练模型"))



if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    # 创建QMainWindow实例
    MainWindow = QtWidgets.QMainWindow()
    # 实例化界面类
    main_window = Ui_xunlian_MainWindow()
    # 将QMainWindow实例传递给setupUi方法
    main_window.setupUi(MainWindow)
    # 显示界面
    MainWindow.show()
    # 启动事件循环
    sys.exit(app.exec_())